# Generated by Django 6.0 on 2025-12-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('in_stock', 'Ex-Stock'), ('check_availability', 'Check Availability'), ('expecting', 'Expecting'), ('special_offer', 'Special Offer'), ('clearance', 'Clearance Price'), ('out_of_stock', 'Out of Stock')], db_index=True, default='in_stock', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='part_number',
            field=models.CharField(blank=True, db_index=True, help_text='Manufacturer part number / Model number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, help_text='Product subcategory within main category', max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['availability'], name='products_pr_availab_bcbf21_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['part_number'], name='products_pr_part_nu_e5d5be_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['subcategory'], name='products_pr_subcate_324098_idx'),
        ),
    ]
