# Generated by Django 6.0 on 2025-12-13 10:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.IntegerField(default=0)),
                ('image', models.URLField(max_length=500)),
                ('images', models.JSONField(blank=True, default=list)),
                ('category_slug', models.CharField(db_index=True, max_length=100)),
                ('subcategory_slug', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('brand_slug', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('supplier_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=255)),
                ('hot', models.BooleanField(db_index=True, default=False)),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('sections', models.JSONField(blank=True, default=dict)),
                ('campaigns', models.JSONField(blank=True, default=dict)),
                ('condition', models.CharField(default='new', max_length=20)),
                ('rating', models.IntegerField(default=0)),
                ('rating_count', models.IntegerField(default=0)),
                ('stock_quantity', models.IntegerField(db_index=True, default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('feature_list', models.JSONField(blank=True, default=list)),
                ('extra_attributes', models.JSONField(blank=True, default=dict)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('long_description', models.TextField(blank=True)),
                ('description_blocks', models.JSONField(blank=True, default=list)),
                ('service_info', models.JSONField(blank=True, default=dict)),
                ('spec_groups', models.JSONField(blank=True, default=list)),
                ('addons', models.JSONField(blank=True, default=list)),
                ('similar_product_ids', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'products_product',
                'indexes': [models.Index(fields=['category_slug', 'is_active'], name='products_pr_categor_2a5caa_idx'), models.Index(fields=['brand_slug', 'is_active'], name='products_pr_brand_s_300d7f_idx'), models.Index(fields=['hot', 'is_active'], name='products_pr_hot_5aa714_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('image_url', models.URLField(max_length=500)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='commands.product')),
            ],
            options={
                'db_table': 'products_productimage',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('processor', models.CharField(blank=True, max_length=255)),
                ('ram', models.CharField(blank=True, max_length=100)),
                ('storage', models.CharField(blank=True, max_length=100)),
                ('screen', models.CharField(blank=True, max_length=100)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('generation', models.CharField(blank=True, max_length=50)),
                ('printer_type', models.CharField(blank=True, max_length=50)),
                ('features', models.JSONField(blank=True, default=list)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='commands.product')),
            ],
            options={
                'db_table': 'products_productspecification',
            },
        ),
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True)),
                ('user_id', models.UUIDField()),
                ('user_name', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='commands.product')),
            ],
            options={
                'db_table': 'products_productrating',
                'unique_together': {('product', 'user_id')},
            },
        ),
    ]
