# Generated by Django 6.0 on 2025-12-23 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, max_length=200, unique=True)),
                ('imei', models.CharField(blank=True, db_index=True, max_length=200, null=True, unique=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('returned', 'Returned')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serial_numbers', to='orders.orderitem')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serial_numbers', to='products.productvariant')),
            ],
            options={
                'indexes': [models.Index(fields=['serial_number'], name='inventory_s_serial__e6e8fe_idx'), models.Index(fields=['imei'], name='inventory_s_imei_cf0ba8_idx'), models.Index(fields=['status'], name='inventory_s_status_4d8d9e_idx')],
                'unique_together': {('imei',), ('serial_number',)},
            },
        ),
    ]
